### PR TITLE
Add Contributors List in about page

### PR DESCRIPTION
**Pull request by SARAN-thala**
Right now the contributors list stored in JSON file. we can’t get directly from github api they rate limit of 60req/hour. 

This is will solve issue #128

### CODE REVIEW

**Comment by NitinNair89** [comment]
> Right now the contributors list stored in JSON file. we can’t get directly from github api they rate limit of 60req/hour.
> 
> This is will solve issue #128

We don't need GitHub API. You can use native JavaScript to read the JSON file and present the data from it.

**Comment by maniac-tech** [comment]
As @NitinNair89  mentioned, I have already created a JSON file and I'm reading it from JS and printing the data.

Maybe @SARAN-thala can build on top of that?

**Comment by SARAN-thala** [comment]
Yeah, I read data from the local JSON file only

**Comment by SARAN-thala** [comment]
This is how it looks 
Screenshot 2019-10-02 at 6 20 56 PM

**Comment by SARAN-thala** [comment]
It closed #97 aswell

**Pull request merged**
