### PR TITLE
Revamped footer

### PR DESCRIPTION
**Pull request by iryanjan18**
Revamped footer to make it responsive

### CODE REVIEW

**Comment by iryanjan18** [comment]
On it.

**Comment by iryanjan18** [comment]
Update pushed to footer branch for merge review

**Comment by iryanjan18** [comment]
Let me know if changes made is ok with you or if you have other request.

**Comment by NitinNair89** [comment]
> Let me know if changes made is ok with you or if you have other request.

Resolve conflicts and push your changes again.

**Comment by iryanjan18** [comment]
Changes made were pushed

**Comment by iryanjan18** [comment]
I'm really sorry about that. Latest commit should now fix the conflict.

**Comment by Evie-Skinner18** [comment]
Thanks so much for your contribution @iryanjan18 ! :100:

**Pull request merged**
