### PR TITLE
update navbar and footer

### PR DESCRIPTION
**Pull request by 0xmeetdev**
improved and fixed the bugs in the footer and navbar . Hope You Like It :)
Here is how it looks -
Screenshot from 2019-10-04 10-38-36

### CODE REVIEW

**Comment by NitinNair89** [comment]
> improved and fixed the bugs in the footer and navbar . Hope You Like It :)
> Here is how it looks -
> Screenshot from 2019-10-04 10-38-36

What happens when we click the "Connect us" button?

**Comment by BlackDevil98** [comment]
right now it is deactivate but we can add the function like notification and feedback and etc.

**Comment by NitinNair89** [comment]
> right now it is deactivate but we can add the function like notification and feedback and etc.

Ok, please add those functions and resend PR after resolving conflicts.

**Comment by BlackDevil98** [comment]
i can't do notification function but i can implement the feedback or suggetion function in website which will give by anyone. You receive all suggestions in mail so I want your gmail Id...

**Comment by BlackDevil98** [comment]
Hello @NitinNair89 ! What do you think about this PR ? Because you can't response to last commit.. So what do you think? I improve or it's a good ?

**Comment by NitinNair89** [comment]
> Hello @NitinNair89 ! What do you think about this PR ? Because you can't response to last commit.. So what do you think? I improve or it's a good ?

You have to pull the latest code to your fork repo, fix conflicts and then push the code changes again. The footer in your screenshot looks good.

**Comment by BlackDevil98** [comment]
All set..Code is done. now suggestion service is off but if you want to it just add your email id in the form tag.

**Comment by BlackDevil98** [comment]
It's right or not ? if not i make some changes in the site.. @nimitpatel ans me please other wise i work on different projects..

**Comment by NitinNair89** [comment]
You have to pull the latest version of the code to your forked repo. And then fix conflicts and add your code changes. If you scroll down, you can see the list of conflicting files.

**Pull request closed without merging**
