### PR TITLE
New features

### PR DESCRIPTION
**Pull request by jerilMJ**
Changes Made:

    + Added new content ( Cartoon neighbor) to index.html ( a canvas animation )
    + Added styles for new content in styles.css
    + Added script for new content in scripts.js
    + Fixed some issues in styles.css and scripts.js

### CODE REVIEW

**Comment by NitinNair89** [comment]
Can you show screenshots of how the site looks after your code changes?

**Comment by Evie-Skinner18** [comment]
Hi @jerilMJ , thanks very much for contributing this! Please can you put it in a brand new html page? index.html is getting far too busy :rocket:    Cheers

**Comment by jerilMJ** [comment]
Of course! I'll get working on it soon!

**Comment by jerilMJ** [comment]
Here are the screenshots:
ss1
ss2

**Comment by Evie-Skinner18** [comment]
Having a git problem but will merge asap

**Pull request merged**
