### PR TITLE
jump to top of page

### PR DESCRIPTION
**Pull request by hosseinSafari**
I have created a button that makes the page jump to the top of the page.

### CODE REVIEW

**Comment by NitinNair89** [comment]
Please resolve conflicts

**Comment by hosseinSafari** [comment]
hosseinSafari:patch-1

**Comment by Evie-Skinner18** [comment]
Hey @hosseinSafari , thanks very much for this helpful contribution! Not keen on having JavaScript embedded in the HTML so please can you rebase, move your JS to a separate file, and update your PR? Cheers 🐶

**Comment by hosseinSafari** [comment]
Yes, I do it tommorow (;

**Comment by Evie-Skinner18** [comment]
@hosseinSafari just noticed there's also CSS embedded in <style> tags, please can you move that to a separate CSS file aswell? styles.css is a good shout

**Comment by Evie-Skinner18** [comment]
Thanks so much for making this contribution!

**Pull request merged**
