### PR TITLE
Added Contributor's page

### PR DESCRIPTION
**Pull request by maniac-tech**
This branch will add a new contributor's page to the website.
Changes made are as follows:

- Created contributors.html
- Created contributors.json
- Added Link to Navbar

### CODE REVIEW

**Comment by maniac-tech** [comment]
Closes #126 

Please review this PR @Evie-Skinner18 @NitinNair89

**Comment by NitinNair89** [comment]
Can you show how it looks?

**Comment by maniac-tech** [comment]
Shall I post a screenshot here? @NitinNair89 
Or do you want to be hosted somewhere?

**Comment by NitinNair89** [comment]
> Shall I post a screenshot here? @NitinNair89
> Or do you want to be hosted somewhere?

You can add GitHub page for your forked repository and share screenshot here as well. I usually follow that approach for static websites.

I prefer GitHub pages though, that way we can test all functionalities.

**Comment by maniac-tech** [comment]
@NitinNair89 :

https://maniac-tech.github.io/happy_hacktoberfest_19/contributors.html

**Comment by NitinNair89** [comment]
Should I close this PR since the other one was merged?

**Comment by NitinNair89** [comment]
Closing this PR as we need an urgent fix. It's under development by @maniac-tech and I would review and merge as needed. :slightly_smiling_face:

**Comment by maniac-tech** [comment]
So we are scraping the Idea of having a separate Contributions page here?

**Comment by NitinNair89** [comment]
> So we are scraping the Idea of having a separate Contributions page here?

No we are not. I merged the PR sent by @SARAN-thala . Should I merge this one as well? We will do it after the layout fix.

**Comment by maniac-tech** [comment]
Or otherwise, can we have the `About` page renamed to `Contributors` and have a separate About page up?

What say @SARAN-thala ?

**Comment by NitinNair89** [comment]
@maniac-tech I think we can have "About" as a bookmark and put the about section in the landing page itself. So clicking on the about link would just scroll the page to the about section. We may not have enough content to put up in the about section apart from describing this repo.

**Comment by maniac-tech** [comment]
Sounds good to me 👍

**Comment by NitinNair89** [comment]
> > So we are scraping the Idea of having a separate Contributions page here?
> 
> No we are not. I merged the PR sent by @SARAN-thala . Should I merge this one as well? We will do it after the layout fix.

After the layout fix, please update this PR as well so that we can publish the contributors page

**Comment by maniac-tech** [comment]
Alright, just to summarize, once the Layout's PR has been merged into master, we will update the pages here to point to the contributions page which @SARAN-thala  has developed. The about section will be made a sub-component of the main website and not a standalone page due to lack of content.

Sounds right @NitinNair89 ?

**Comment by NitinNair89** [comment]
> Alright, just to summarize, once the Layout's PR has been merged into master, we will update the pages here to point to the contributions page which @SARAN-thala has developed. The about section will be made a sub-component of the main website and not a standalone page due to lack of content.
> 
> Sounds right @NitinNair89 ?

Yes, that's correct.

**Pull request merged**
