### PR TITLE
corrected the navbar position

### PR DESCRIPTION
**Pull request by dipanshu231099**

### CODE REVIEW

**Comment by NitinNair89** [comment]
Hi @dipanshu231099 - Does this change fix the positioning issue?

**Comment by dipanshu231099** [comment]
> Hi @dipanshu231099 - Does this change fix the positioning issue?

yes sir it does. the position is such that it stick to the top of the website now

**Comment by dipanshu231099** [comment]
@NitinNair89 kindly review

**Comment by NitinNair89** [comment]
I am not sure if changing ```<header>``` tag to ```<navbar>``` tag fixes position issue. It was probably due to incorrect CSS which was fixed in one of the previous commits.

Closing this PR. If you have any improvements, please open an issue and describe details. :slightly_smiling_face:

**Comment by dipanshu231099** [comment]
@NitinNair89 sir this is exactly due to navbar tag

**Comment by dipanshu231099** [comment]
you may see both the different forms previous and after to prove my point

**Comment by NitinNair89** [comment]
> you may see both the different forms previous and after to prove my point
> Kindly merge as i think if it is closed as such it wont give me any advantage in hacktoberfest

Hi @dipanshu231099 - ```<navbar>``` is not a valid HTML tag btw :slightly_smiling_face: 

You can report and work on any other issues to improve this repo.

**Pull request closed without merging**
